import Image from "next/image";
import { CorridorChip } from "@/components/product/CurrencyChip";
import { CorridorMap } from "@/components/product/CorridorMap";
import { Reveal } from "@/components/motion/Reveal";

const MARQUEE_CORRIDORS = [
  { from: "NGN", to: "RWF" },
  { from: "GHS", to: "KES" },
  { from: "XAF", to: "NGN" },
  { from: "RWF", to: "NGN" },
  { from: "KES", to: "GHS" },
  { from: "NGN", to: "XAF" },
  { from: "RWF", to: "GHS" },
  { from: "KES", to: "NGN" },
];

/* Real swap cards generated by Akara's own card renderer. */
const EXAMPLE_CARDS = [
  {
    src: "/cards/listing-001.webp",
    alt: "Akara swap card: I have 350,000 NGN, I need 412,500 RWF — open AKR-LIST-001 on Akara to swap",
  },
  {
    src: "/cards/listing-002.webp",
    alt: "Akara swap card: I have 4,800 GHS, I need 48,900 KES — open AKR-LIST-002 on Akara to swap",
  },
  {
    src: "/cards/listing-003.webp",
    alt: "Akara swap card: I have 350,798 XAF, I need 800,000 NGN — open AKR-LIST-003 on Akara to swap",
  },
  {
    src: "/cards/listing-004.webp",
    alt: "Akara swap card: I have 1,260,000 RWF, I need 1,850,000 NGN — open AKR-LIST-004 on Akara to swap",
  },
];

function MarqueeRow() {
  return (
    <ul className="flex shrink-0 items-center gap-3 pr-3">
      {MARQUEE_CORRIDORS.map((c) => (
        <li key={`${c.from}-${c.to}`}>
          <CorridorChip from={c.from} to={c.to} />
        </li>
      ))}
    </ul>
  );
}

export function CorridorBoard() {
  return (
    <div className="flex flex-col gap-12">
      <Reveal>
        <div className="marquee-mask overflow-hidden" aria-label="Example currency corridors">
          <div className="marquee-track flex w-max">
            <MarqueeRow />
            <div aria-hidden="true">
              <MarqueeRow />
            </div>
          </div>
        </div>
      </Reveal>

      <Reveal delay={0.08}>
        <CorridorMap />
      </Reveal>

      <div className="grid gap-5 sm:grid-cols-2">
        {EXAMPLE_CARDS.map((card, i) => (
          <Reveal key={card.src} delay={i * 0.07}>
            <div className="overflow-hidden rounded-2xl ring-1 ring-white/10 transition-all duration-500 hover:-translate-y-1 hover:ring-brand/40 hover:shadow-[0_24px_64px_rgba(0,0,0,0.6)]">
              <Image
                src={card.src}
                alt={card.alt}
                width={2000}
                height={1000}
                loading="lazy"
                className="h-auto w-full"
                sizes="(max-width: 640px) 100vw, 560px"
              />
            </div>
            <p className="mt-2 text-center text-[10px] uppercase tracking-[0.18em] text-faint">
              Example listing — not a live rate
            </p>
          </Reveal>
        ))}
      </div>
    </div>
  );
}
